### ISSUE TITLE
Probes not passing when domain is set to subpath/subfolder

### ISSUE THREAD

**Issue by lord-kyron** [gissilabs/charts#27]
Hi @sgissi ,
I am trying to deploy the helm chart on a domain, that I am going to use with subpath. For example https://domain.com/vault/
The problem here seems to me to be in the current config of the probes of deployment:
```
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: HTTP
```
With this setup when enter in values.yaml https://example.com/vault as my domain, the probes are failing with:
```
Readiness probe failed: HTTP Probe failed with statuscode: 404
Liveness probe failed: HTTP Probe failed with statuscode: 404
```
However, when I change this value to my domain only, without the subpath - https://example.com - the probes are passing and the deployment is up, however because I am running behind nginx reverse proxy it seems not working well and some stuff are broken other stuff tries to redirect me to the main domain, not to the subpath that I am using.
Can you fix this and make those probes config exposed in the values yaml for example to be able to configure the path and try to fix this issue this way or make it to take it dynamically from the input of the domain value?

Thanks!
