### ISSUE TITLE
Allow environment variables from secret in Vaultwarden chart

### ISSUE THREAD

**Issue by nico151999** [gissilabs/charts#55]
I have just come across this chart and there is one important detail I would like to see. I would like to set environment variables based on the values in existing secrets.

For backwards compatibility I am thinking about keeping `vaultwarden.extraEnv` as it is for hardcoded environment variables and introducing a new variable in values.yaml. One way of doing it would be a variable that expects the exact same format that a pod also expects, so that one can simply insert the parameters 1:1 and the users can decide themselves if they would like to reference a config map, a secret or yet something else. However, in that case I would propose deprecating `vaultwarden.extraEnv` and let it live on for some time in parallel to a new `vaultwarden.extraEnvs`.

However, the current implementation of `vaultwarden.extraEnv` applies a key-value pair syntax. Therefore, I would suggest to do something similar with a new secret reference which I would call `vaultwarden.extraEnvFromSecretKey`. The values could looks as follows:
```yaml
vaultwarden:
  extraEnvFromSecretKey:
    MY_FIRST_VARIABLE:
      name: my-secret
      key: my-first-secret-key
    MY_SECOND_VARIABLE:
      name: my-secret
      key: my-second-secret-key
```

If you are open for a PR I am willing to implement it. Looking forward to a response. Can't wait to implement this chart into my home setup 😃
