### ISSUE TITLE
Upgrade vaultwarden application version to latest release

### ISSUE THREAD

**Issue by raidlman** [gissilabs/charts#65]
Vaultwarden 1.33 is available since Jan 25 so I guess it makes sense to also upgrade your charts to the latest version available (1.33.2).

**Comment by erikmagkekse** [comment]
+Upvote from me

PS: As workaround you can specify the new image tag in your values file.

```
image:
  pullPolicy: IfNotPresent
  repository: vaultwarden/server
  tag: "1.33.2"
```
